version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./:/language_course/
    ports:
      - 5430:5432
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=BESTPASSWORD
      - POSTGRES_DB=lang_course_db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db